var constants = {
    ACTION_ADD_ITEM: 'ACTION_ADD_ITEM',
    ACTION_EDIT_ITEM: 'ACTION_EDIT_ITEM',
    ACTION_DELETE_ITEM: 'ACTION_DELETE_ITEM',
    ACTION_LIST_ITEM: 'ACTION_CART_ITEM',
    ACTION_DETAIL_ITEM: 'ACTION_DETAIL_ITEM',
    ACTION_DELETECART_ITEM: 'ACTION_DELETECART_ITEM',
}
module.exports = constants;
